version: "2"
services:
    app:
      image: registry.code.go1.com.au/fn/es-writer:${CI_BUILD_REF_NAME}
      mem_limit: $MEM
      environment:
      - RABBITMQ_URL
      - RABBITMQ_KIND
      - RABBITMQ_EXCHANGE
      - RABBITMQ_ROUTING_KEY
      - ELASTIC_SEARCH_URL
      command: [
          "/app/app",
          "-prefetch-count", "50",
          "-prefetch-size", "0",
          "-queue-name", "es-writter",
          "-queue-name", "es-writter"
      ]
