[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/jmespath/go-jmespath"
  version = "0.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"

[[constraint]]
  name = "gopkg.in/olivere/elastic.v5"
  version = "5.0.72"

[prune]
  go-tests = true
  unused-packages = true
