[[constraint]]
  name = "github.com/jmespath/go-jmespath"
  version = "0.2.2"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.3"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"

[[constraint]]
  name = "gopkg.in/olivere/elastic.v5"
  version = "5.0.81"

[prune]
  go-tests = true
  unused-packages = true
